// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt2ws34DZmbIma9ZyTpkn2Qyunr8laS0Q',
    appId: '1:828647961526:web:cde79d1885a6a405bf4717',
    messagingSenderId: '828647961526',
    projectId: 'ecomerce-8be97',
    authDomain: 'ecomerce-8be97.firebaseapp.com',
    storageBucket: 'ecomerce-8be97.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCJYt6FBbIQaviak21VBa5mqOruz2fHYQ',
    appId: '1:828647961526:android:12fd1d5d5cde1745bf4717',
    messagingSenderId: '828647961526',
    projectId: 'ecomerce-8be97',
    storageBucket: 'ecomerce-8be97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpUkz3Bl4JU4eTuWcRUY_lXXY4d42H1MI',
    appId: '1:828647961526:ios:e80e9ddcb799f628bf4717',
    messagingSenderId: '828647961526',
    projectId: 'ecomerce-8be97',
    storageBucket: 'ecomerce-8be97.appspot.com',
    iosBundleId: 'com.fsh.ecommerce',
  );
}
